platform :ios, '7.0'

pod 'Parse'
pod 'ParseFacebookUtils'
pod 'Facebook-iOS-SDK'
pod 'AFNetworking'
pod 'Reachability'
pod 'UIAlertView+Blocks'
pod 'JASidePanels'
pod 'AsyncImageView'
pod 'MWPhotoBrowser'
pod 'CTAssetsPickerController'
pod 'Mixpanel'
